// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "hello.proto" (package "hello", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HelloGrpc } from "./hello";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HelloReply } from "./hello";
import type { HelloRequest } from "./hello";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service hello.HelloGrpc
 */
export interface IHelloGrpcClient {
    /**
     * @generated from protobuf rpc: SayHello(hello.HelloRequest) returns (hello.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply>;
}
/**
 * @generated from protobuf service hello.HelloGrpc
 */
export class HelloGrpcClient implements IHelloGrpcClient, ServiceInfo {
    typeName = HelloGrpc.typeName;
    methods = HelloGrpc.methods;
    options = HelloGrpc.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SayHello(hello.HelloRequest) returns (hello.HelloReply);
     */
    sayHello(input: HelloRequest, options?: RpcOptions): UnaryCall<HelloRequest, HelloReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HelloRequest, HelloReply>("unary", this._transport, method, opt, input);
    }
}
