// @generated by protobuf-ts 2.9.4 with parameter optimize_code_size
// @generated from protobuf file "users.proto" (package "mouse", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message mouse.UserName
 */
export interface UserName {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string;
}
/**
 * @generated from protobuf message mouse.UsersList
 */
export interface UsersList {
    /**
     * @generated from protobuf field: repeated mouse.User users = 1;
     */
    users: User[];
}
/**
 * @generated from protobuf message mouse.User
 */
export interface User {
    /**
     * @generated from protobuf field: uint64 id = 1;
     */
    id: bigint;
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string;
    /**
     * @generated from protobuf field: string createdAt = 3;
     */
    createdAt: string; // TODO: should we use timestamp time instead ? https://protobuf.dev/best-practices/dos-donts/#well-known-common
}
/**
 * @generated from protobuf message mouse.UserChange
 */
export interface UserChange {
    /**
     * @generated from protobuf field: mouse.SessionAction action = 1;
     */
    action: SessionAction;
    /**
     * @generated from protobuf field: uint64 userId = 2;
     */
    userId: bigint;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
}
/**
 * @generated from protobuf enum mouse.SessionAction
 */
export enum SessionAction {
    /**
     * @generated from protobuf enum value: ACTION_UNSPECIFIED = 0;
     */
    ACTION_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: JOIN = 1;
     */
    JOIN = 1,
    /**
     * @generated from protobuf enum value: LEAVE = 2;
     */
    LEAVE = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class UserName$Type extends MessageType<UserName> {
    constructor() {
        super("mouse.UserName", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message mouse.UserName
 */
export const UserName = new UserName$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UsersList$Type extends MessageType<UsersList> {
    constructor() {
        super("mouse.UsersList", [
            { no: 1, name: "users", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => User }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message mouse.UsersList
 */
export const UsersList = new UsersList$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("mouse.User", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "createdAt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message mouse.User
 */
export const User = new User$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UserChange$Type extends MessageType<UserChange> {
    constructor() {
        super("mouse.UserChange", [
            { no: 1, name: "action", kind: "enum", T: () => ["mouse.SessionAction", SessionAction] },
            { no: 2, name: "userId", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message mouse.UserChange
 */
export const UserChange = new UserChange$Type();
/**
 * @generated ServiceType for protobuf service mouse.UsersService
 */
export const UsersService = new ServiceType("mouse.UsersService", [
    { name: "Join", options: {}, I: UserName, O: UsersList },
    { name: "GetUsersEvents", serverStreaming: true, options: {}, I: Empty, O: UserChange }
]);
